#!/bin/bash

if [ $# -lt 1 ];then
  echo "Usage: $0 [aws subcmd]"
  exit 1
fi

$@ help | \
  awk  -F'[ \t\f\n\r\v]' 'BEGIN{f=0} \
       {if($0 ~ /[A-Z].*[A-Z].*[A-Z]/){f++;a[f]=$0}else{a[f]=a[f]"___"$0}}\
     END{for(n in a){if(a[n] ~ /A.*V.*A.*I/){gsub("___","\n",a[n]);print n,a[n]}}}' | \
  awk '/o/{print $NF}'
