#!/bin/bash

if [ -f aws-region.txt ];then
  target=$(ls -l --time-style='+%Y%m%d' aws-region.txt | awk '{print $6}')
  today=$(date '+%Y%m%d')
  if [ $(( ${today} - ${target})) -ge 1 ];then
    rm aws-region.txt
  fi
fi

if [ ! -f aws-region.txt ];then
  w3m -cols 240 -dump "https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/UserGuide/using-regions-availability-zones.html" | \
  awk 'BEGIN{a=0} \
         {if($1 ~ /コード/&& $2 ~ /名前/){a=1}else{if($1 ~ /詳細/){a=0}}} \
         {if(a==1&& !/^$|lax-/){gsub("不要|必要|必須|利用不可|オプトインステータス|ローカルゾーン","",$0); \
           printf "%-18s%s%s%s\n",$1,$2,$3,$4}}' > aws-region.txt
fi
